"""empty message

Revision ID: bc2b9b2ae3b2
Revises: c3e66e1b8986
Create Date: 2024-08-30 14:13:40.327458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2b9b2ae3b2'
down_revision: Union[str, None] = 'c3e66e1b8986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
